"""Per-slot hermes-adapter config — single source of truth shared by the SSH
(real) and local-Docker (mock) provisioners. Mirrors docs/ARCHITECTURE.md §5 and
CLAUDE.md "hermes contract": ONE adapter container, ports 8766/9000,
`API_SERVER_KEY` auth, /opt/data + /workspaces volumes. The user's `.env` is
injected verbatim and NEVER persisted (D12)."""

from __future__ import annotations

from backend.config import Settings
from backend.providers.base import Slot


def container_name(slot_name: str) -> str:
    return f"slot-{slot_name}"


def build_env(
    slot: Slot,
    *,
    settings: Settings,
    agent_api_key: str,
    display_name: str,
    user_env: dict[str, str],
) -> dict[str, str]:
    """Non-secret hermes contract env + the user's secret env layered on top.
    Reserved keys can't be overridden by user input."""
    base = {
        "HERMES_ADAPTER_HOST": "0.0.0.0",
        "HERMES_ADAPTER_PORT": str(settings.agent_workspace_port),
        "A2A_HOST": "0.0.0.0",
        "A2A_PORT": str(settings.agent_a2a_port),
        "A2A_PUBLIC_URL": slot.a2a_url,
        "API_SERVER_KEY": agent_api_key,  # == PRD AKELA_API_KEY (D6)
        "AGENT_NAME": display_name,
        "HERMES_WORKSPACE_DIR": settings.agent_workspace_dir,
        "HERMES_HOME": settings.agent_hermes_home,
    }
    reserved = set(base)
    for k, v in user_env.items():
        if k not in reserved:  # never let user input clobber the contract
            base[k] = v
    return base


def render_compose(slot: Slot, *, settings: Settings, display_name: str, host_dir: str) -> str:
    """The docker-compose.yml the SSH provisioner writes on the agent VPS. Secrets
    come from a root-only `.env` beside it (referenced via env_file), never a DB."""
    return f"""# generated by akela-host — slot {slot.slot_name}
services:
  agent:
    image: {settings.hermes_adapter_image}
    container_name: {container_name(slot.slot_name)}
    restart: unless-stopped
    environment:
      HERMES_ADAPTER_HOST: 0.0.0.0
      HERMES_ADAPTER_PORT: {settings.agent_workspace_port}
      A2A_HOST: 0.0.0.0
      A2A_PORT: {settings.agent_a2a_port}
      A2A_PUBLIC_URL: {slot.a2a_url}
      AGENT_NAME: {display_name}
      HERMES_WORKSPACE_DIR: {settings.agent_workspace_dir}
      HERMES_HOME: {settings.agent_hermes_home}
    env_file: [{host_dir}/.env]   # root-only; API_SERVER_KEY + user secrets; never in any DB
    volumes:
      - {host_dir}/data:{settings.agent_hermes_home}
      - {host_dir}/workspaces:{settings.agent_workspace_dir}
    ports:
      - "{settings.agent_workspace_port}"
      - "{settings.agent_a2a_port}"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{settings.agent_workspace_port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
"""
